<h1><?php echo $this->titulo; ?></h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url . '/application/formulario/recibe',
    'method' => 'post',
    'class' => 'form-horizontal',
));
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Suba su Foto: </label> 
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $img = $form->get('file');
        //echo $formLabel->openTag() . $pass->getOption('label');
        echo $this->formInput($img);
        //echo $this->formElementErrors($name);
        //echo $formLabel->closeTag();
        ?>
    </div>
</div>
<hr/>
<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Nombre: </label> 
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $name = $form->get('nombre');
        //echo $formLabel->openTag() . $name->getOption('label');
        echo $this->formInput($name);
        //echo $formLabel->closeTag();
        //echo $this->formElementErrors($name);
        ?>
    </div>
</div>

<!--<div class="item form-group"> 
        <?php //aqui para poner a prueba un decorador..
        //$correo = $form->get('correo');
        //echo $formLabel->openTag() . $correo->getLabel('label');
        //echo $this->formInput($correo);
        //echo $this->formElementErrors($correo);
        //echo $formLabel->closeTag();
        ?> 
</div>-->

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">E-mail: </label> 
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $mail = $form->get('email');
        //echo $formLabel->openTag() . $name->getOption('label');
        echo $this->formInput($mail);
        //echo $this->formElementErrors($name);
        //echo $formLabel->closeTag();
        ?>
    </div>
</div>
<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Password: </label> 
    <?php
    //echo $formLabel->openTag() . $pass->getOption('label') . $pass->getLabelAttributes('class');
    //echo $formLabel->setAttributes(array('class' => 'col-md-3'));
    //echo $formLabel->closeTag();
    ?>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $pass = $form->get('pass');
        echo $this->formInput($pass);
        //echo $this->formElementErrors($name);
        ?>
    </div>
</div>
<hr/>
<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Genero: </label> 
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $gender = $form->get('sexo');
        //echo $formLabel->openTag().$gender->getLabel();
        //echo $formLabel->closeTag();
        echo $this->formRadio($gender);
        echo $this->formElementErrors($gender);
        ?>
    </div>
</div>
<hr/>
<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Lenguaje: </label> 
    <?php
    //echo $formLabel->openTag() . $lenguaje->getLabel('label');
    // echo $formLabel->getLabelAttribute($lenguaje);
    // echo $formLabel->closeTag();
    ?>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $lenguaje = $form->get('lenguaje');
        echo $this->formSelect($lenguaje);
        echo $this->formElementErrors($lenguaje);
        ?>
    </div>
</div>  

<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Pais: </label> 
    <?php
    //echo $formLabel->openTag() . $pais->getLabel('label');
    // echo $formLabel->getLabelAttribute($pais);
    // echo $formLabel->closeTag();
    ?>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $pais = $form->get('pais');
        echo $this->formSelect($pais);
        echo $this->formElementErrors($pais);
        ?>
    </div>
</div>  
<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Preferencias: </label> 
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $preferencias = $form->get('preferencias');
        //echo $formLabel->openTag().$preferencias->getLabel();
        //echo $formLabel->closeTag();
        echo $this->formMultiCheckbox($preferencias);
        echo $this->formElementErrors($preferencias);
        ?>
    </div>
</div>
<hr/>
<div class="item form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">&nbsp;</label> 
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php
        $condiciones = $form->get('condiciones');
        echo $formLabel->openTag().$condiciones->getLabel();
        echo $formLabel->closeTag();
        echo $this->formCheckbox($condiciones);
        echo $this->formElementErrors($condiciones);
        ?>
    </div>
</div>
<hr />
<?php echo $this->formHidden($form->get('oculto')); ?>
<div style="text-align: center;" class="a-center">
    <?php
    //echo $this->formElement($form->get('security')); para el captcha
    echo $this->formElement($form->get('send'));
    echo $this->form()->closeTag($form);
    ?>
</div>

