<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Peligro\Module'                        => __DIR__ . '/Module.php',
    'Peligro\Controller\IndexController' => __DIR__ . '/src/Peligro/Controller/IndexController.php',
    'Peligro\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'Peligro\SampleTest'                => __DIR__ . '/tests/Peligro/SampleTest.php',
);